#!/bin/bash


efi () {
	sudo umount /dev/"$DEV"* &> /dev/null
	sudo dd if="$DIR"/src/EFI.iso of=/dev/"$DEV" bs=10M count=1000 status=progress
	
	sudo umount /dev/"$DEV"* &> /dev/null
	(echo r; echo d; echo w; echo Y;) | sudo gdisk /dev/"$DEV"

	sudo umount /dev/"$DEV"* &> /dev/null 
	(echo d; echo 2;  echo n; echo 2; echo ""; echo ""; echo N; echo w;) | sudo fdisk /dev/"$DEV"
	
	sudo umount /dev/"$DEV"* &> /dev/null
	yes | sudo e2fsck -f /dev/$"$DEV"2 -p

	sudo umount /dev/"$DEV"* &> /dev/null
	sudo resize2fs /dev/$"$DEV"2
}

mbr () {
	sudo umount /dev/"$DEV"* &> /dev/null
	sudo dd if="$DIR"/src/"$ISOv".iso of=/dev/"$DEV" bs=10M count=1000 status=progress
	
	sudo umount /dev/"$DEV"* &> /dev/null
	(echo d; echo n; echo p; echo 1; echo ""; echo ""; echo "n"; echo w;) | sudo fdisk /dev/"$DEV"
	sudo umount /dev/"$DEV"* &> /dev/null
	sudo e2fsck -f /dev/$"$DEV"1

	sudo umount /dev/"$DEV"* &> /dev/null
	sudo resize2fs /dev/$"$DEV"1
}

#------------------------------------------------------------------------------------------------------------------

sudo ls > /dev/null

clear
lsblk | grep "^[^loop]"
read -p 'Device: ' DEV
if [ $DEV = "sda" ]
then
	echo "Bad move"
	exit 1	
fi
clear

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

read -p 'EFI or MBR: ' BOOT
if [ $BOOT = "EFI" ]
then
	efi
fi
if [ $BOOT = "MBR" ]
then
	read -p 'Laptop(MBR_L) or Desktop(MBR):' ISOv
	mbr
fi

echo "END"




