#!/bin/bash

DEV=$1
IF=$2

sudo umount /dev/"$DEV"* &> /dev/null
sudo dd if="$IF" of=/dev/"$DEV" bs=10M count=1000 status=progress

sudo umount /dev/"$DEV"* &> /dev/null
(echo r; echo d; echo w; echo Y;) | sudo gdisk /dev/"$DEV"

sudo umount /dev/"$DEV"* &> /dev/null 
(echo d; echo 2;  echo n; echo 2; echo ""; echo ""; echo N; echo w;) | sudo fdisk /dev/"$DEV"

sudo umount /dev/"$DEV"* &> /dev/null
yes | sudo e2fsck -f /dev/$"$DEV"2 -p

sudo umount /dev/"$DEV"* &> /dev/null
sudo resize2fs /dev/$"$DEV"2
