#!/bin/bash

DEV=$1
IF=$2

sudo umount /dev/"$DEV"* &> /dev/null
sudo dd if="$IF" of=/dev/"$DEV" bs=10M count=1000 status=progress

sync
sleep 3

sudo umount /dev/"$DEV"* &> /dev/null
printf ", +" | sudo sfdisk -N 1 /dev/"$DEV"

sync
sleep 0.5

sudo umount /dev/"$DEV"* &> /dev/null
sudo e2fsck -f /dev/$"$DEV"1

sync
sleep 0.5

sudo umount /dev/"$DEV"* &> /dev/null
sudo resize2fs /dev/$"$DEV"1




