#!/bin/bash

DEV=$1
IF=$2

sudo umount /dev/"$DEV"* &> /dev/null
sudo dd if="$IF" of=/dev/"$DEV" bs=10M count=1000 status=progress

sudo umount /dev/"$DEV"* &> /dev/null
(echo d; echo n; echo p; echo 1; echo ""; echo ""; echo "n"; echo w;) | sudo fdisk /dev/"$DEV"
sudo umount /dev/"$DEV"* &> /dev/null
sudo e2fsck -f /dev/$"$DEV"1

sudo umount /dev/"$DEV"* &> /dev/null
sudo resize2fs /dev/$"$DEV"1




